### ISSUE TITLE
Criar dashboards no Kibana

### ISSUE THREAD

**Issue by MarthaDs** [proepidesenvolvimento/guardioes-web#10]
**Descrição**

Para melhorar a visualização e analise dos dados é necessário criar dashboard no kibana, onde é possível visualizar de maneira rápida e objetiva os dados existentes na API.

**Tarefas**

- [x] Configurar o kibana
- [ ] Definir quais dashboard devem ser criados
- [ ] Criar os dashboards
- [x] Verificar se os dados estão sendo apresentados corretamente

**Critérios de aceitação**

- [ ] Ser possível visualizar os dados da API, corretamente, nos dashboards criados.

**Comment by guilacerda** [comment]
Inicialmente o plano traçado foi refazer as visualizações já existentes no Guardiões Web no Kibana. 

A imagem abaixo mostra que o dashboard existente já está desenvolvido no kibana de desenvolvimento. Acredito que devam ser criadas issues separadas para as próximas visualizações decididas e linkadas na issue #1.

![image](https://user-images.githubusercontent.com/26297247/78094752-b286c500-73ab-11ea-80c7-9060c8ab8718.png)
