### ISSUE TITLE
Erro ao acessar painel

### ISSUE THREAD

**Issue by ViniciusPuerto** [proepidesenvolvimento/guardioes-web#112]
**Descrição do erro encontrado:**
Quando acesso o painel tenho minha tela cortada.

**Passo a passo para a reprodução do erro:**
Especificações do passo a passo para a reprodução do erro encontrado
1. primeiro passo
Acessar o painel como um GroupManager

<img width="1418" alt="Captura de Tela 2020-10-23 às 17 47 29" src="https://user-images.githubusercontent.com/41026043/97052914-45f63200-1558-11eb-9c27-8243c2ae618a.png">

**Comportamento esperado:** Aparecer a tela completa.
**Comportamento obtido:** A tela apresenta um corte na parte inferior.

Device:
Macbook Pro (Retina, 13", Mid 2014)
13,3 polegadas (2560 x 1600)

**Comment by alvesitalo** [comment]
Corrigido quando o PR #122 for aceito.
