### ISSUE TITLE
Bordas azuis em torno dos campos

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-web#116]
**Descrição do erro encontrado:**
Aparição de bordas ao clicar nos botões, dropmenu, text inputs.

**Passo a passo para a reprodução do erro:**
Especificações do passo a passo para a reprodução do erro encontrado
1. primeiro passo: Acessar o painel
2. segundo passo: Selecionar qualquer botão, campo ou menu.

<img width="1546" alt="Captura de Tela 2020-10-23 às 18 05 07" src="https://user-images.githubusercontent.com/41026043/97054078-8060ce80-155a-11eb-86f6-3f62fea1c957.png">

**Comportamento esperado:** Não aparecer as bordas.
**Comportamento obtido:** Bordas azuis apareceram ao selecionar o campo

**Comment by alvesitalo** [comment]
Corrigido com o PR #123
