### ISSUE TITLE
Configurar Redux

### ISSUE THREAD

**Issue by ViniciusPuerto** [proepidesenvolvimento/guardioes-web#15]
**Descrição**

Preparar a aplicação para usarmos o [redux](https://redux.js.org/), apenas adicionando as pastas e arquivos iniciais referentas as actions, reducers, types e etc.

**Tarefas**

- [ ] Pasta e referentes `index.js` para `actions, constants, reducers, store`. 

**Critérios de aceitação**

- [ ] Cada pasta e seu referente

**Comment by victorgcramos** [comment]
Fala mano! Se precisar de ajuda com alguma dúvida, pode falar! Eu recomendaria utilizar hooks ao invés do redux pra essa aplicação, ja que ela é bem simples. Abraços!
