### ISSUE TITLE
Problema ao editar Sintomas, Síndromes, Conteúdos e Usuários.

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-web#153]
**Descrição do erro encontrado:**
Ao realizar login como Admin, Manager ou GroupManager. Ao tentar realizar a edição Sintomas, Síndromes, Conteúdos e Usuários é retornado que o usuário não tem permissão para tal.

Para Manager, foi verificado que ele possui as devidas permissões.

**Passo a passo para a reprodução do erro:**
Especificações do passo a passo para a reprodução do erro encontrado
1. Logar como Admin, Manager (precisa possuir permissão de Sintomas ou Síndromes ou Conteúdos ou Usuários) ou GroupManager (Edita apenas Usuários );
2. Acessar a página Sintomas ou Síndromes ou Conteúdos ou Usuários;
3. Tentar realizar a Edição de alguma dessa funcionalidades;
...

**Comportamento esperado:** Que a edição se concretiza-se.
**Comportamento obtido:** É retornado que o usuário não possui permissão para tal ação.

Captura de Tela:
Logado como groupManager com permissão.
<img width="1440" alt="Captura de Tela 2020-11-19 às 15 49 56" src="https://user-images.githubusercontent.com/41026043/99711545-a78abd00-2a80-11eb-8d92-dd39812411ca.png">

**Comment by gsmartins96** [comment]
Corrigido no [PR](https://github.com/proepidesenvolvimento/guardioes-api/pull/210) feito na API
