### ISSUE TITLE
Listagem dos Usuários

### ISSUE THREAD

**Issue by gsmartins96** [proepidesenvolvimento/guardioes-web#155]
**Descrição**
Retornar somente usuários do **mesmo app_id** do _tipo de usuário logado_
Ou seja:

Se usuário logado for: 
**ADMIN**
 - Retornar usuários com mesmo app_id do ADMIN

**MANAGER**
 - Retornar usuários com mesmo app_id do MANAGER

**GROUP MANAGER**
 - Retorna somente usuários cadastrado na instituição do GROUP MANAGER

**Comment by gabrieldouurado** [comment]
A parte de Admin e Manager foi resolvida no PR [#221](https://github.com/proepidesenvolvimento/guardioes-api/pull/221) do repositório guardioes-api
