### ISSUE TITLE
Remover menus para Admin(is_god: False) e Manager

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-web#213]
**Descrição**
Remover os menus de "Vigilância Ativa" e "Instituições" para um administrador is_god: false e Gerentes

**Tarefas**
- [x] Remover menus para esse caso;
- [x] Verificar o porque esses menus apareceram, uma vez que para um admin (is_god: true) eles não estavam presentes;
- [x] Deixar os menus "congelados" de modo que ao adicionar um novo menu, ele não apareça para esse caso. É importante que ainda seja possível inserir novos menus para esse caso.

**Comment by alvesitalo** [comment]
O admin (is_god: true) não aparecia os dois menus porque na NavBar, o método slice() que pega partes do array que tem todos os menus, tava recebendo o final em -2 (que remove os 2 últimos objetos).
![Captura de tela de 2021-01-15 10-25-59](https://user-images.githubusercontent.com/35741521/104735883-ece60680-5720-11eb-9571-7f58ab0a64f9.png)
Pra manter o comportamento igual a partir de agora, tem sempre que adicionar os novos menus antes desses 2 objetos.
