### ISSUE TITLE
Dashboard para Perguntas de Biossegurança

### ISSUE THREAD

**Issue by gabrieldouurado** [ProEpiDesenvolvimento/guardioes-web#248]
**Descrição**
Desenvolver um dashboard para apresentar os dados colhidos a partir das perguntas de biossegurança.

**Tarefas**
- [x] Definir junto ao profissionais de saúde quais serão os indicadores;
- [x] Produzir os gráficos;
- [x] Implementar o dashboard na página de Biossegurança.

**Indicadores**
- [x] Total de pessoas que responderam o questionário
- [x] Total de perguntas do questionário
- [x] Total de respostas do questionário
- [x] Total de pessoas que responderam o formulário por dia
- [x] Gráficos de Pizza para cada pergunta

**Critérios de aceitação**
- [x] Realização de todas as tarefas.

**Comment by gabrieldouurado** [comment]
Aguardando Indicadores.

**Comment by alvesitalo** [comment]
@gabrieldouurado Indicadores adicionados
