### ISSUE TITLE
Página de gestão de equipe para groupManager.

### ISSUE THREAD

**Issue by jps12** [proepidesenvolvimento/guardioes-web#274]
**Descrição**
Criar de uma página em que possa ser possível criar/editar/apagar o groupManagerTeam.<br>
Deve ser possível atribuir permissões a esse tipo de usuário.
GroupManagerTeam deve herdar o APP_ID do groupManager.

**Tarefas**

- [x] Listar todos os GroupManagerTeams.
- [x] Editar cada GroupManagerTeam.
- [x] Criar cada GroupManagerTeam.
- [x] Apagar cada GroupManagerTeam.
- [x] Editar permissão.

**Critérios de aceitação**

- [x] Mostrar confirmação para cada uma dessas ações.
- [x] Não permitir que seja criado GroupManagerTeam com campos vazios.
- [x] Ao ser criado um novo GroupManagerTeam deve-se atualizar a lista.

**Comment by gabrieldouurado** [comment]
1. Na página de administradores, não deve aparecer Equipe de Grupo
2. Na página de Equipe de Instituição, logado como groupManager, ao editar um GroupManagerTeam, as informações não são atualizadas na página (teste: editar o nome do GMT, ver que ao editar o nome não é atualizado)
3. Ao clicar em editar e selecionar uma permissão, ocorre um erro, conforma a imagem abaixo
![Captura de Tela 2021-06-23 às 16.59.15.png](https://images.zenhubusercontent.com/5d7eeb7d9e6efa0001036ae3/07008aa3-d1cd-4759-9627-93edfa829d5c)
4. Ao criar um novo GMT as permissão não são persistidas

**Comment by alvesitalo** [comment]
@gabrieldouurado Creio que está tudo funcionando agora, adicionei um delay entre editar um GroupManagerTeam e dar GET em todos novamente, porque por algum motivo ainda vinha os valores antigos.
