### ISSUE TITLE
Campo instituições aparecendo para admins

### ISSUE THREAD

**Issue by jps12** [proepidesenvolvimento/guardioes-web#286]
**Descrição do erro encontrado:**
Quando o admin tem o campo is_god=false, aparece para ele o componente de instituições. E quando entra lá, aparece erro de autenticação. O esperado era que não aparecesse esse componente. 

**Passo a passo para a reprodução do erro:**
Especificações do passo a passo para a reprodução do erro encontrado
1. Logar como admin em que o campo *is_god=false*
2. Navegar até o campo de instituições. 

**Comportamento esperado:** Não aparecer o campo instituições.
**Comportamento obtido:** Aparece o campo instituições, e dá erro de autenticação.

**Comment by alvesitalo** [comment]
Adicionei a correção desse problema em um PR que está linkado com essa issue.
