### ISSUE TITLE
Criação do layout do painel de gerenciamento.

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-web#41]
Definir o layout que será utilizado no painel.

Layout anterior:
https://xd.adobe.com/view/30098027-f175-43cb-4335-945c2d8018e4-4638/screen/4332a8ed-5762-43a2-8b30-eeb25285ffdd

Critérios de Aceitação:
- [ ]Protótipo;
- [ ]Implementação.

**Comment by ViniciusPuerto** [comment]
Estamos fazendo o design nas ultimas tela no [Figma](https://www.figma.com/file/RyUywd7xSkGU5OwnZ848Gb/Untitled?node-id=0%3A1)

**Comment by tsrrodrigues** [comment]
O PR #59 fecha essa issue.
