### ISSUE TITLE
Protótipos de telas Painel

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-web#42]
Criar prototipos de telas com base no layout definido na issue #41.

Visualização de admin.

Critérios de Aceitação:
- [ ] Protótipo da tela gerenciamento de manager.
- [x] Protótipo da tela gerenciamento de sintomas.
- [ ] Protótipo da tela gerenciamento de síndromes.
- [x] Protótipo da tela gerenciamento de Conteúdos.
- [x] Protótipo da tela gerenciamento de usuários.

**Comment by ViniciusPuerto** [comment]
Quase todas as telas foram prototipadas, algumas faltaram pois tinham algumas diferenças e peculiaridades 

[Prototipos no figma](https://www.figma.com/file/RyUywd7xSkGU5OwnZ848Gb/Untitled?node-id=0%3A1)
