### ISSUE TITLE
Refatoração da tela de pre-cadastro

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-web#43]
Retirar as informações sobre o projeto da tela de pré-cadastro

Critérios de Aceitação:
- [x] Tela de pré-cadastro sem informações

**Comment by tsrrodrigues** [comment]
A tela home foi desfeita, agora o usuário entra automaticamente na tela de pré-cadastro. A imagem da tela de pré-cadastro foi substituída por um título e subtítulo.
