### ISSUE TITLE
Estudar forma de criar as Dashboards por instuições 

### ISSUE THREAD

**Issue by ViniciusPuerto** [proepidesenvolvimento/guardioes-web#58]
# Descrição

Precisamos ques as visualisações de dados sejam mostradas de acordo com os grupos.

## Tarefas

- [x] Estudar o [Metabase](https://www.metabase.com/) para usá-lo como alternativa ao Kibana
- [ ] Estudar o [Bitergia](https://github.com/Bitergia) também como opção de solução

## Critérios

- [ ] Uma proposta de solução para as visualisações

**Comment by RenatoBrittoAraujo** [comment]
A Metabase tem dois problemas:

- A mesma limitação que o Kibana, não permite a seleção específica de dados dentro da tabela, apenas a tabela inteira.
- Além disso, não possui os dashboards guardados em que alguém pode acessar e ver em tempo real gráficos e dados.

**Comment by RenatoBrittoAraujo** [comment]
Estou estudando a possibilidade de segmentar as tabelas por indices na tabela.
-> https://stackoverflow.com/questions/63399918/is-there-a-way-to-create-phantom-tables-in-a-postgres-database

**Comment by RenatoBrittoAraujo** [comment]
A segmentação de tabelas por indicies pelo postgres não é possível de forma a atender as demandas.

Estou estudando a segmentação dos dados passados para o kibana. -> https://github.com/ankane/searchkick#reference
