### ISSUE TITLE
Criação de user para a configuração do Elasticsearch.

### ISSUE THREAD

**Issue by MarthaDs** [proepidesenvolvimento/guardioes-web#6]
**Descrição**

Para que seja feita as devidas configurações no servidor é necessário a criação de um user que tenha permissão de instalação de pacotes. 

**Tarefas**

- [x] Criar elasticsearch user.

**Critérios de aceitação**

- [x] Ser possível acessar o servidor com o usuário criado
- [x] Ser possível instalar pacotes com o usuário criado.

**Comment by GesielFreitas** [comment]
1. sudo adduser **nomedousuario**
    1. nome do usuario colocar um nome valido para o usuario do elasticseach
    2. o unix irá te guiar pedindo algumas informações  como: senha, nome_completo etc.., Não precisa preencher todas mas a senha e nome completo sim.
   3. confimar e pronto usuario criado
   4. adicionar ele no grupo do root para poder instalar os pacotes necessarios para o elastic

######
1. sudo usermod -aG sudo **nomedousuario**

Pronto.
