### ISSUE TITLE
Integrar Navegação com Componentes

### ISSUE THREAD

**Issue by ViniciusPuerto** [proepidesenvolvimento/guardioes-web#62]
**Descrição**

No nosso menu temos como selecionar várias telas para o usuário pode administrar assim o componente deve ser renderizado no meio da tela conforme fosse selecionado no menu.

**Tarefas**

- [ ] Usar o navbar para renderizar os componentes

**Critérios de aceitação**

- [ ] Renderizar o componente selecionado
- [ ] Permitir que apenas um componente seja marcado

**Comment by tsrrodrigues** [comment]
O PR #59 fecha essa issue.
