### ISSUE TITLE
Coordenadas no Kibana

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-web#75]
**Descrição**
Levar as coordenadas dos surveys para Kibana. Gerar um mecanismo que reduza a precisão dessas coordenadas.

**Critérios de aceitação**

- [x] Coordenadas no painel do Kibana
- [x] Mecanismo de precisão

**Comment by RenatoBrittoAraujo** [comment]
Consertado pelo PR na API: https://github.com/proepidesenvolvimento/guardioes-api/pull/168
