### ISSUE TITLE
Configuração do elasticsearch

### ISSUE THREAD

**Issue by MarthaDs** [proepidesenvolvimento/guardioes-web#8]
**Descrição**

Apoś instalação é importante fazer a configuração do elasticsearch dentro do servidor. Deve ser estudado quais as configurações mínimas são necessárias serem feitas para que o elastic consiga conversar com a API já existente. 

**Tarefas**

- [x] Saber quais configurações devem ser feitas. (Link da documentação [aqui](https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html))
- [x] Fazer as configurações
- [x] Testar se o elastic funciona corretamente

**Critérios de aceitação**

- [x] Elasticsearch rodando corretamente
- [x] Ter testado uma busca e/ou indexação.

Obs.: Como não sabemos ainda se a API está estável para conversar com elastic seria interessante testar as configurações antes de fazer a conexão entre eles.

**Comment by guilacerda** [comment]
As issues foram resolvidas no https://github.com/proepidesenvolvimento/guardioes-api . Explicação está na #1 .

**Comment by guilacerda** [comment]
A partir do docker foi possível subir rapidamente uma imagem do ElasticSearch, e como a API foi desenvolvida em Ruby on Rails, foi usada uma Gem chamada Searchkick que automatiza muita a integração com o ElasticSearch.

**Comment by guilacerda** [comment]
Agora basta ver a demanda pra saber quais indexes usar pra executar as querys.
