### ISSUE TITLE
Integração do Kibana no Painel de Gerenciamento

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-web#82]
**Descrição**
Inserir os dashboard do kibana no painel de gerenciamento.

**Critérios de aceitação**
- [x] Dashboard mostrar apenas os dados da instituição que logou na API.

**Comment by ViniciusPuerto** [comment]
https://discuss.elastic.co/t/login-to-kibana-via-api/120101
Parece que nessa discussão eles tratam justamente o que nós queremos né @gabrieldouurado @RenatoBrittoAraujo ??

**Comment by RenatoBrittoAraujo** [comment]
Muito interessante esse link, quando a página estiver na branch vou tentar implementar isso.

Talvez isso também possa ser usado para fazer o dashboard público.

**Comment by RenatoBrittoAraujo** [comment]
Após a criação do proxy reverso do nginx, uma ideia me ocorreu:

pelo browser, talvez seja possível fazer o fowarding da autenticação para o proxy reverso, e esse usar essa autenticação para dar acesso aos dados.

**Comment by RenatoBrittoAraujo** [comment]
Não foi possível fazer o que foi comentado no anterior, pois browsers modernos não permite passa esse header pelo Iframe.
