### ISSUE TITLE
Estilizar telas de visualizações

### ISSUE THREAD

**Issue by ViniciusPuerto** [proepidesenvolvimento/guardioes-web#89]
**Descrição**
Na parte de dashboards já temos os frames do kibana embutidos mas eles de uma forma bagunçada, o objetivo dessa tarefa é fazer com que os paineis do kibana sejam apresentados de forma mais agradavel, seja paginando eles ou de outra forma

**Tarefas**

- [x] Disponibiliar os paineis mais organizadamente, como por exemplo paginando eles

**Critérios de aceitação**

- [x] Tela de visualizações estilizada e organizada

**Comment by alvesitalo** [comment]
Atualmente as visualizações estão assim:
![Dashboard Kibana(Laptop with MDPI screen)](https://user-images.githubusercontent.com/35741521/94746988-5568cd80-0354-11eb-8b8c-1c55e1cf718a.png)
