### ISSUE TITLE
Integração da API  com o elasticsearch

### ISSUE THREAD

**Issue by MarthaDs** [proepidesenvolvimento/guardioes-web#9]
**Descrição**

Fazer a integração da API com elasticsearch para criação dos dashboards no kibana.

**Tarefas**

- [ ] Verficar requisistos minimos para a integração
- [ ] Estudar e definir passo a passo a ser seguido para a integração
- [ ] Seguir passos definidos para fazer a integração
- [ ] Verificar se a integração foi realizada e está funcionando corretamente.

**Critérios de aceitação**

- [ ] Se possível deixar registrado o passo a passo para posteridades
- [ ] Fazer uma busca e/ou indexação na API usando o elasticsearch

**Comment by MarthaDs** [comment]
Link da documentação do elastic sobre REST APIs [aqui](https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-apis.html)

**Comment by guilacerda** [comment]
É melhor a api fazer a inserção dos dados diretos no ElasticSearch ao invés do próprio elastic fazer requisições na api. Por isso as issues referentes ao ElasticStack estão sendo resolvidas no repositório https://github.com/proepidesenvolvimento/guardioes-api
